import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../public/jev-player.html', import.meta.url), 'utf8');
const moduleScript = [...html.matchAll(/<script type="module">([\s\S]*?)<\/script>/g)][0]?.[1];

test('Jev player dashboard renders auditable loot and funding evidence', () => {
  assert.ok(moduleScript, 'module script exists');
  assert.match(html, /<pre id="choice-funnel">/);
  assert.match(moduleScript, /choiceAudit.auditedAt/);
  assert.match(moduleScript, /providerSelectionRateAmongEligibleMenus/);
  assert.match(moduleScript, /finalSelectionRateAmongEligibleMenus/);
  assert.match(moduleScript, /providerSelectionRateAmongOneRankAdvancingMenus/);
  assert.match(moduleScript, /finalSelectionRateAmongOneRankAdvancingMenus/);
  assert.match(moduleScript, /rankSensitivityUnknownObservations/);
  assert.match(moduleScript, /STALE relative to the live run heartbeat/);
  assert.match(html, /node scripts\/jev-player-loop-audit.mjs --run RUN_ID --save/);
  assert.match(html, /<pre id="loot">/);
  assert.match(html, /<pre id="queue">/);
  assert.match(moduleScript, /trace\.harvestedCounts/);
  assert.match(moduleScript, /trace\.soldCounts/);
  assert.match(moduleScript, /Tracked unsold stock/);
  assert.match(moduleScript, /Current purse/);
  assert.match(moduleScript, /Campaign target/);
  assert.match(moduleScript, /Provider backoffs/);
  assert.match(moduleScript, /Circuit breaks/);
  assert.match(moduleScript, /RT-free combat windows/);
  assert.match(moduleScript, /Rank point rate/);
  assert.match(moduleScript, /Gate-row closure rate/);
  assert.match(moduleScript, /Stalled choice pass-throughs/);
  assert.match(moduleScript, /Repeat-override release threshold/);
  assert.match(moduleScript, /Repeated-choice releases/);
  assert.match(moduleScript, /supervisorReleaseReason/);
  assert.match(moduleScript, /RT ability prefetches/);
  assert.match(moduleScript, /RT ability commands dispatched/);
  assert.match(moduleScript, /RT ability cancellations/);
  assert.match(moduleScript, /rtAbilityPrefetchMinHpFraction/);
  assert.match(moduleScript, /RT ability deferrals/);
  assert.match(moduleScript, /Stale RT action skips/);
  assert.match(moduleScript, /Dragon Form offers/);
  assert.match(moduleScript, /Dragon Form selections/);
  assert.match(moduleScript, /Dragon Form RT refusals/);
  assert.match(moduleScript, /Dragon Form uses \(Inner Fire drop inferred\)/);
  assert.match(moduleScript, /import \{ JevEventMonitor, JevEventTraceReader \} from '\.\/js\/jev-event-monitor\.js'/);
  assert.match(moduleScript, /new JevEventMonitor\(\)/);
  assert.match(moduleScript, /new JevEventTraceReader\(eventMonitor\)/);
  assert.match(moduleScript, /eventTraceReader\.refresh\(run,root\+'\/events\.jsonl'\)/);
  assert.doesNotMatch(moduleScript, /fetch\(root\+'\/events\.jsonl'/,
    'the dashboard must not redownload the full event trace every refresh');
  assert.match(moduleScript, /Decision provider/);
  assert.match(moduleScript, /Preserved Jev choices/);
  assert.match(moduleScript, /Committed-lane mindstate advances/);
  assert.match(moduleScript, /providerChoice=x\.providerChoice/);
  assert.match(moduleScript, /laneCoachPreservedProviderChoice/);
  assert.match(moduleScript, /jev-player-lane-coach-v29-after-v28-20260921\.json/);
  assert.match(moduleScript, /jev-player-control-v28-after-v12-v19-20260921\.json/);
  assert.match(moduleScript, /V28 control:/);
  assert.match(moduleScript, /V28 queue record/);
  assert.match(moduleScript, /V29 lane-coach comparison/);
  assert.match(moduleScript, /Distinct skill lanes ranked/);
  assert.match(moduleScript, /import \{ distinctLaneSummary \} from '\.\/js\/jev-gate-summary\.js'/);
  assert.match(moduleScript, /distinctLaneSummary\(req,m\.vitals\?\.skills/);
  assert.match(moduleScript, /trace\.gateHistory\.at\(-1\)/);
  assert.match(moduleScript, /Jev decisions/);
  assert.match(moduleScript, /Local decisions/);
  assert.match(moduleScript, /local-decision/);
  assert.match(moduleScript, /local-error/);
  assert.match(moduleScript, /error\.provider===\(m\.provider\|\|'jev'\)/);
  assert.match(moduleScript, /Recent \$\{m\.provider\|\|'Jev'\} decisions/);
  assert.match(moduleScript, /m\.status==='complete'&&!m\.progression\?\.targetReached/,
    'legacy time-capped manifests are not presented as campaign successes');
  const inlineBody=moduleScript.replace(/^import .*;\s*/gm,'');
  assert.doesNotThrow(() => new Function(inlineBody), 'inline module body parses');
});
